/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    ErrorPage: typeof import('./src/views/ErrorPage.vue')['default']
    HomePage: typeof import('./src/views/HomePage.vue')['default']
    LayoutDefault: typeof import('./src/layouts/LayoutDefault.vue')['default']
    NotFoundPage: typeof import('./src/views/NotFoundPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteLogomark: typeof import('./../common/src/components/SiteLogomark.vue')['default']
    SiteLogotype: typeof import('./../common/src/components/SiteLogotype.vue')['default']
    ThemePage: typeof import('./src/views/ThemePage.vue')['default']
  }
}
