/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountMenu: typeof import('./src/components/AccountMenu.vue')['default']
    AccountMenuButton: typeof import('./src/components/AccountMenuButton.vue')['default']
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    BreakpointName: typeof import('./src/layouts/BreakpointName.vue')['default']
    ErrorPage: typeof import('./src/views/ErrorPage.vue')['default']
    FirstPage: typeof import('./src/views/FirstPage.vue')['default']
    HelpMenu: typeof import('./src/components/HelpMenu.vue')['default']
    HelpMenuButton: typeof import('./src/components/HelpMenuButton.vue')['default']
    HomePage: typeof import('./src/views/HomePage.vue')['default']
    LayoutDefault: typeof import('./src/layouts/LayoutDefault.vue')['default']
    LoadingProgress: typeof import('./src/components/LoadingProgress.vue')['default']
    ManagementDrawer: typeof import('./src/layouts/ManagementDrawer.vue')['default']
    NotFoundPage: typeof import('./src/views/NotFoundPage.vue')['default']
    NotifySnackbar: typeof import('./src/components/NotifySnackbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondPage: typeof import('./src/views/SecondPage.vue')['default']
    SiteLogomark: typeof import('./src/components/SiteLogomark.vue')['default']
    SiteLogotype: typeof import('./src/components/SiteLogotype.vue')['default']
    ThemePage: typeof import('./src/views/ThemePage.vue')['default']
    ToggleDarkButton: typeof import('./src/layouts/ToggleDarkButton.vue')['default']
  }
}
