/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteLogomark: typeof import('./../common/src/components/SiteLogomark.vue')['default']
    SiteLogotype: typeof import('./../common/src/components/SiteLogotype.vue')['default']
  }
}
