/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CoverImage: typeof import('./src/components/CoverImage.vue')['default']
    CtaBtn: typeof import('./src/components/CtaBtn.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    GitHubIcon: typeof import('./src/components/GitHubIcon.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    PageSection: typeof import('./src/components/PageSection.vue')['default']
    PageSections: typeof import('./src/components/PageSections.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section_capabilities: typeof import('./src/components/sections/section_capabilities.vue')['default']
    Section_case_studies: typeof import('./src/components/sections/section_case_studies.vue')['default']
    Section_differentiators: typeof import('./src/components/sections/section_differentiators.vue')['default']
    Section_hero: typeof import('./src/components/sections/section_hero.vue')['default']
    Section_tours: typeof import('./src/components/sections/section_tours.vue')['default']
    SectionTitle: typeof import('./src/components/SectionTitle.vue')['default']
    SiteLogomark: typeof import('./../common/src/components/SiteLogomark.vue')['default']
    SiteLogotype: typeof import('./../common/src/components/SiteLogotype.vue')['default']
    VCardAction: typeof import('vuetify/components')['VCardAction']
  }
}
